POST http://localhost:3006/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhbmlVTSIsImlkIjoiNjcyYmY1MDMwNWRlNTg2YTYyNTRkMjFiIiwiaWF0IjoxNzMxMDE2OTU1fQ.MamSQBZfOmoEvonQ6-Nr_ilBMeBvr8rCCruSONvqAo0

{"title": "El hombre WEWEWREererer",
    "author": "Daniel uiwnwdsadasdsax",
    "url": "udhud879sdadsa78",
    "likes": 521
    }